### ISSUE TITLE
New Item

### ISSUE THREAD

**Issue by sitasreturn** [Waoweens/WaoTweaks#4]
I want a God's Golden Sword in this mod as a joke item and it's ony obtainable by using commands

**Comment by Skytoon50** [comment]
cool

**Comment by Waoweens** [comment]
what does the item do?

**Comment by Waoweens** [comment]
Name: God's Golden Sword
Damage: 2147483647
Durability: Unbreakable

**Comment by Waoweens** [comment]
added
